In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('BreastCancer.csv')
df.columns =['Sample code number', 'Clump Thickness', 'Uniformity of Cell Size', 'Uniformity of Cell Shape','Marginal Adhesion','Single Epithelial Cell Size','Bare Nuclei','Bland Chromatin','Normal Nucleoli','Mitoses','Class']
df.head()

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0             1002945                5                        4   
1             1015425                3                        1   
2             1016277                6                        8   
3             1017023                4                        1   
4             1017122                8                       10   

   Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                         4                  5                            7   
1                         1                  1                            2   
2                         8                  1                            3   
3                         1                  3                            2   
4                        10                  8                            7   

  Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0          10                3                2        1      2  
1           2                3                1        1      2  
2           4                3                7        1      2  
3           1                3                1        1      2  
4          10                9                7        1      4

In [4]:
df.shape

(698, 11)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 698 entries, 0 to 697
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   Sample code number           698 non-null    int64 
 1   Clump Thickness              698 non-null    int64 
 2   Uniformity of Cell Size      698 non-null    int64 
 3   Uniformity of Cell Shape     698 non-null    int64 
 4   Marginal Adhesion            698 non-null    int64 
 5   Single Epithelial Cell Size  698 non-null    int64 
 6   Bare Nuclei                  698 non-null    object
 7   Bland Chromatin              698 non-null    int64 
 8   Normal Nucleoli              698 non-null    int64 
 9   Mitoses                      698 non-null    int64 
 10  Class                        698 non-null    int64 
dtypes: int64(10), object(1)
memory usage: 60.1+ KB


In [6]:
df.isna().sum()

Sample code number             0
Clump Thickness                0
Uniformity of Cell Size        0
Uniformity of Cell Shape       0
Marginal Adhesion              0
Single Epithelial Cell Size    0
Bare Nuclei                    0
Bland Chromatin                0
Normal Nucleoli                0
Mitoses                        0
Class                          0
dtype: int64

In [7]:
(df.values=='?').sum()

16

In [11]:
(df.values==np.NaN).sum()

0

In [12]:
df.replace('?',np.NaN,inplace=True)

In [15]:
df.isna().sum()

Sample code number              0
Clump Thickness                 0
Uniformity of Cell Size         0
Uniformity of Cell Shape        0
Marginal Adhesion               0
Single Epithelial Cell Size     0
Bare Nuclei                    16
Bland Chromatin                 0
Normal Nucleoli                 0
Mitoses                         0
Class                           0
dtype: int64

In [19]:
df.dropna(inplace=True)

In [20]:
df.isna().sum().sum()

0

In [25]:
df = df.astype(float)
zscore = np.abs((df-df.mean())/df.std())
out = zscore > 3
df = df[~out.any(axis=1)]
df

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0             1002945.0              5.0                      4.0   
1             1015425.0              3.0                      1.0   
2             1016277.0              6.0                      8.0   
3             1017023.0              4.0                      1.0   
4             1017122.0              8.0                     10.0   
..                  ...              ...                      ...   
693            776715.0              3.0                      1.0   
694            841769.0              2.0                      1.0   
695            888820.0              5.0                     10.0   
696            897471.0              4.0                      8.0   
697            897471.0              4.0                      8.0   

     Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                         4.0                5.0                          7.0   
1                         1.0                1.0                          2.0   
2                         8.0                1.0                          3.0   
3                         1.0                3.0                          2.0   
4                        10.0                8.0                          7.0   
..                        ...                ...                          ...   
693                       1.0                1.0                          3.0   
694                       1.0                1.0                          2.0   
695                      10.0                3.0                          7.0   
696                       6.0                4.0                          3.0   
697                       8.0                5.0                          4.0   

     Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0           10.0              3.0              2.0      1.0    2.0  
1            2.0              3.0              1.0      1.0    2.0  
2            4.0              3.0              7.0      1.0    2.0  
3            1.0              3.0              1.0      1.0    2.0  
4           10.0              9.0              7.0      1.0    4.0  
..           ...              ...              ...      ...    ...  
693          2.0              1.0              1.0      1.0    2.0  
694          1.0              1.0              1.0      1.0    2.0  
695          3.0              8.0             10.0      2.0    4.0  
696          4.0             10.0              6.0      1.0    4.0  
697          5.0             10.0              4.0      1.0    4.0  

[629 rows x 11 columns]

In [27]:
df['Class'].unique()

array([2., 4.])

In [29]:
df.loc[df['Class']==2,'Class']='B'
df.loc[df['Class']==4,'Class']='M'
df.head()

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0           1002945.0              5.0                      4.0   
1           1015425.0              3.0                      1.0   
2           1016277.0              6.0                      8.0   
3           1017023.0              4.0                      1.0   
4           1017122.0              8.0                     10.0   

   Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                       4.0                5.0                          7.0   
1                       1.0                1.0                          2.0   
2                       8.0                1.0                          3.0   
3                       1.0                3.0                          2.0   
4                      10.0                8.0                          7.0   

   Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses Class  
0         10.0              3.0              2.0      1.0     B  
1          2.0              3.0              1.0      1.0     B  
2          4.0              3.0              7.0      1.0     B  
3          1.0              3.0              1.0      1.0     B  
4         10.0              9.0              7.0      1.0     M

In [32]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(df['Class'])
y

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,

In [34]:
from sklearn.preprocessing import StandardScaler
x = df.drop('Class',axis=1)
x = x[x>=0]
scaler = StandardScaler()
x = scaler.fit_transform(x)
x

array([[-0.1627774 ,  0.29489048,  0.4322558 , ..., -0.10148976,
        -0.21602519, -0.33753272],
       [-0.11966894, -0.44705396, -0.64524314, ..., -0.10148976,
        -0.56623097, -0.33753272],
       [-0.11672596,  0.6658627 ,  1.86892106, ..., -0.10148976,
         1.53500372, -0.33753272],
       ...,
       [-0.55698836,  0.29489048,  2.58725369, ...,  2.08471096,
         2.58562106,  0.96497085],
       [-0.52710605, -0.07608174,  1.86892106, ...,  2.95919124,
         1.18479794, -0.33753272],
       [-0.52710605, -0.07608174,  1.86892106, ...,  2.95919124,
         0.48438637, -0.33753272]])

In [36]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=42)

In [39]:
y_train

array([1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,

In [40]:
y_test

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0])

In [41]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
lr = LogisticRegression()
lr.fit(X_train,y_train)
y_predict = lr.predict(X_test)
LRAccuracy = accuracy_score(y_test,y_predict)

In [42]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(X_train,y_train)
y_predict = nb.predict(X_test)
NBAcurracy = accuracy_score(y_test,y_predict)

In [46]:
print("Logistic Regression Accuracy:", LRAccuracy)
print("Naive Bayes Accuracy:", NBAcurracy)

Logistic Regression Accuracy: 0.9556962025316456
Naive Bayes Accuracy: 0.9620253164556962
